using Content.Client.Stylesheets.Fonts;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class AccessibilityTab : Control
{
    public AccessibilityTab()
    {
        RobustXamlLoader.Load(this);

        Control.AddOptionCheckBox(CCVars.AccessibilityColorblindFriendly, ColorblindFriendlyCheckBox);
        Control.AddOptionCheckBox(CCVars.ReducedMotion, ReducedMotionCheckBox);
        Control.AddOptionPercentSlider(CCVars.ScreenShakeIntensity, ScreenShakeIntensitySlider);
        Control.AddOptionPercentSlider(CCVars.ChatWindowOpacity, ChatWindowOpacitySlider);
        Control.AddOptionPercentSlider(CCVars.SpeechBubbleTextOpacity, SpeechBubbleTextOpacitySlider);
        Control.AddOptionCheckBox(CCVars.ChatAutoFillHighlights, AutoFillHighlightsCheckBox);
        Control.AddOptionColorSlider(CCVars.ChatHighlightsColor, HighlightsColorSlider);

        Control.AddOptionCheckBox(CCVars.AccessibilityClientCensorNudity, CensorNudityCheckBox);

        // Font stuff
        Control.AddOptionFontScale(FontCVars.MainScale, MainFontSelector);
        Control.AddOptionFontFamilyName(FontCVars.MainFamilyName, MainFontSelector);
        Control.AddOptionFontScale(FontCVars.TitleScale, TitleFontSelector);
        Control.AddOptionFontFamilyName(FontCVars.TitleFamilyName, TitleFontSelector);
        Control.AddOptionFontScale(FontCVars.MachineTitleScale, MachineTitleFontSelector);
        Control.AddOptionFontFamilyName(FontCVars.MachineTitleFamilyName, MachineTitleFontSelector);
        Control.AddOptionFontScale(FontCVars.MonospaceScale, MonospaceFontSelector);
        Control.AddOptionFontFamilyName(FontCVars.MonospaceFamilyName, MonospaceFontSelector);
        Control.AddOptionFontScale(FontCVars.ChatScale, ChatFontSelector);
        Control.AddOptionFontFamilyName(FontCVars.ChatFamilyName, ChatFontSelector);
        Control.AddOptionFontScale(FontCVars.ChatWhisperScale, ChatWhisperFontSelector);
        Control.AddOptionFontFamilyName(FontCVars.ChatWhisperFamilyName, ChatWhisperFontSelector);
        Control.AddOptionFontScale(FontCVars.ChatEmoteScale, ChatEmoteFontSelector);
        Control.AddOptionFontFamilyName(FontCVars.ChatEmoteFamilyName, ChatEmoteFontSelector);

        Control.Initialize();
    }
}

