- type: job
  id: ESAnimalControl
  name: ESjob-name-animalcontrol
  description: ESjob-description-animalcontrol
  playTimeTracker: ESJobAnimalControl
  startingGear: ESAnimalControlGear
  icon: "ESJobIconAnimalControl"
  access:
  - Custodial
  - Maintenance
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: GarbageDay
    prototype: ESWeaponRevolver357

- type: startingGear
  id: ESAnimalControlGear
  equipment:
    shoes: ClothingShoesSanitation
    id: AnimalControlPDA
    ears: ClothingHeadsetService
    head: ClothingHeadHatKhakiSoft
    gloves: ESClothingHandsGlovesSanitation
    jumpsuit: ClothingUniformJumpsuitAnimalControl
    outer: ClothingOuterJacketCamo
    back: ClothingBackpack
  storage:
    back:
    - ESBoxSurvival

- type: chameleonOutfit
  id: ESAnimalControl
  job: ESAnimalControl
  hidden: false
