- type: job
  id: ESHazmat
  name: ESjob-name-hazmat
  description: ESjob-description-hazmat
  playTimeTracker: ESJobHazmat
  startingGear: ESHazmatGear
  icon: "ESJobIconHazmat"
  access:
  - Custodial
  - Maintenance
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: GarbageDay
    prototype: ESWeaponRevolver357

- type: startingGear
  id: ESHazmatGear
  equipment:
    shoes: ClothingShoesSanitation
    id: HazmatPDA
    ears: ClothingHeadsetService
    gloves: ESClothingHandsGlovesSanitation
    jumpsuit: ClothingUniformJumpsuitHazmat
    back: ClothingBackpack
  storage:
    back:
    - ESBoxSurvival

- type: chameleonOutfit
  id: ESHazmat
  job: ESHazmat
  hidden: false
