using Content.Client._ES.Auditions;
using Content.Client._ES.Core;
using Content.Client.Humanoid;
using Content.Shared._Citadel.Utilities;
using Content.Shared.Body;
using Content.Shared.Clothing;
using Content.Shared.GameTicking;
using Content.Shared.Humanoid;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Roles;
using Content.Shared.Station;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._ES.Spawning.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESJobDisplay : BoxContainer
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPlayerManager _player = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    private readonly ESAuditionsSystem _auditions;
    private readonly SharedVisualBodySystem _visualBody;
    private readonly SharedStationSpawningSystem _stationSpawning;

    private ProtoId<JobPrototype> _jobId;
    private EntityUid _doll;

    public ESJobDisplay()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _auditions = _entityManager.System<ESAuditionsSystem>();
        _visualBody = _entityManager.System<SharedVisualBodySystem>();
        _stationSpawning = _entityManager.System<SharedStationSpawningSystem>();

        SetJob(SharedGameTicker.FallbackOverflowJob);
    }

    public void SetJob(ProtoId<JobPrototype> job)
    {
        _jobId = job;

        var jobProto = _prototypeManager.Index(job);

        NameLabel.Text = Loc.GetString(jobProto.Name);
        DescriptionLabel.UnsafeSetMarkup(jobProto.Description == null
            ? string.Empty
            : Loc.GetString(jobProto.Description));

        _entityManager.DeleteEntity(_doll);
        _doll = jobProto.JobEntity is null
            ? _entityManager.Spawn(_prototypeManager.Index(jobProto.SpeciesOverride ?? HumanoidCharacterProfile.DefaultSpecies).DollPrototype)
            : _entityManager.Spawn(jobProto.JobEntity);
        var randomSeed = new RngSeed().SeedForStep(job.Id.GetHashCode() + _player.LocalEntity?.Id ?? 0);
        var defaultDude = _auditions.RandomProfile(randomSeed.IntoRandomizer(), jobProto.SpeciesOverride, out _);
        _visualBody.ApplyProfileTo(_doll, defaultDude);
        JobView.SetEntity(_doll);

        // HACK SHIT i threw in because idk how this loadout bs works.
        var jobLoadout = LoadoutSystem.GetJobPrototype(job.Id);
        if (_prototypeManager.TryIndex(jobLoadout, out RoleLoadoutPrototype? roleProto))
        {
            var loadout = new RoleLoadout(jobLoadout);
            loadout.SetDefault(new HumanoidCharacterProfile(), null, _prototypeManager);
            _stationSpawning.EquipRoleLoadout(_doll, loadout, roleProto);
        }

        _stationSpawning.EquipStartingGear(_doll, jobProto.StartingGear);
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        SetJob(_jobId);
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _entityManager.DeleteEntity(_doll);
    }
}

